@ Brief
@ Detail [detail]
@ Copyright [copyright]
@ License [license]
@ Author [author]
api Api

@ Brief
@ Detail [detail]
enum Flags [flags]
    const Value1 : 1 @ Doc
    const Value2 : 2 @ Doc
    const Value3 : 4 @ Doc
    const Value4 : 8 @ Doc

@ Brief
@ Detail [detail]
struct Test
    field Field1 {Flags} : Flags.Value1, Flags.Value2, Flags.Value3, Flags.Value4 @ Doc
    field Field2 {Int32} : 1, 2, 3, 4 [array(3)] @ Doc
