@ Brief
@ Detail [detail]
@ Copyright [copyright]
@ License [license]
@ Author [author]
api Api

@ Brief
@ Detail [detail]
enum En
    const Value1 @ Doc
    const Value2 @ Doc

@ Brief
@ Detail [detail]
struct Test
    field Field1 {Int32} : 7 @ Doc
    field Field2 {En} : En @ Doc
