@ Brief
@ Detail [detail]
@ Copyright [copyright]
@ License [license]
@ Author [author]
api Api

@ Brief
enum Test @ Detail
    const Value1 : "Invalid value" @ Detail
    const Value2 : Value1 @ Detail
    const Value3 : Value2 @ Detail
    const Value4 @ Detail
