@ Brief
@ Detail [detail]
@ Copyright [copyright]
@ License [license]
@ Author [author]
api Api [maxenum]

@ Brief
enum Test [countenums] @ Detail
    const Value1 : Value5 @ Detail
    const Value2 : 2 @ Detail
    const Value3 : Value1 @ Detail
    const Value4 : Value2, Value3 @ Detail
    const Value5 : Value4 @ Detail

@ Brief
enum OtherTest @ Detail
    const Value1 @ Detail
    const Value2 : 2 @ Detail
    const Value3 : Value8 @ Detail
    const Value4 @ Detail
    const Value5 @ Detail
    const Value6 : Value4 @ Detall
    const Value7 @ Detail
    const Value8 @ Detail
