@ Brief
@ Detail [detail]
@ Copyright [copyright]
@ License [license]
@ Author [author]
api Api [booltype(Float)]

@ Brief
@ Detail [detail]
struct Test
    field Field1 {Int32} : 4 @ Doc
    field Field2 {Int32} [array(3.5)] @ Doc
    field Field3 {Int32} [array(4, 5)] @ Doc
