@ Brief
@ Detail [detail]
@ Copyright [copyright]
@ License [license]
@ Author [author]
api Api

@ Test function
@ Description [detail]
func Test
    arg String {Str} [const] @ Doc
    arg Integer {Int32} [const] @ Doc
