@ ```
    Brief   \  \atest {Api}   
       te\\st ind\`ent
       test \{A\} Str\[B\]123\n
       OK\````
@ \eDetail\n\nTest\OK\s\s\s  123  \s\s  AAA\tBBB\ [detail]
@    Copyright [copyright]
@ License    [license]
@ ```
    Author
  Indent
  ``` [author]
api Api

@ Brief
@ Detail [detail]
enum Test
    const Value1 @   Test    first doc\sstring
    const Value2 @ ```
        Test multiline
        inline doc for enum {Test}
          of const {Value2}.
        ```
    const Value3 @ Test{Value3}OK.
