function(idl_embed_resources TARGET_NAME)
    set(HEADER_CONTENT "#ifndef AST_RESOURCES_HPP\n#define AST_RESOURCES_HPP\n\n#include <string_view>\n\nnamespace idl::resources {\n")
    foreach(RESOURCE_FILE ${ARGN})
        get_filename_component(FILE_NAME "${RESOURCE_FILE}" NAME)
        string(MAKE_C_IDENTIFIER "${FILE_NAME}" VAR_NAME)
        if(NOT EXISTS "${RESOURCE_FILE}")
            message(FATAL_ERROR "Resource file not found: ${RESOURCE_FILE}")
        endif()
        file(READ "${RESOURCE_FILE}" HEX_DATA HEX)
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1, " BYTE_ARRAY "${HEX_DATA}")
        string(APPEND HEADER_CONTENT "    inline constexpr char ${VAR_NAME}_bytes[] = { ${BYTE_ARRAY} };\n")
        string(APPEND HEADER_CONTENT "    inline constexpr std::string_view ${VAR_NAME}{\n")
        string(APPEND HEADER_CONTENT "        ${VAR_NAME}_bytes, sizeof(${VAR_NAME}_bytes)\n")
        string(APPEND HEADER_CONTENT "    };\n\n")
    endforeach()
    string(APPEND HEADER_CONTENT "}\n\n#endif\n")
    set(OUTPUT_HPP "${CMAKE_CURRENT_BINARY_DIR}/idl_resources.hpp")
    file(GENERATE OUTPUT "${OUTPUT_HPP}" CONTENT "${HEADER_CONTENT}")
    target_include_directories(${TARGET_NAME} PRIVATE "${CMAKE_CURRENT_BINARY_DIR}")
endfunction()
