name: Publish documentation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get install -y graphviz
        wget https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.linux.bin.tar.gz
        tar -xf doxygen-1.12.0.linux.bin.tar.gz
        cd doxygen-1.12.0
        sudo make
        sudo make install
        doxygen --version

    - name: Set build output dir
      id: strings
      shell: bash
      run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
  
    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}
        -DIDLC_BUILD_DOC=ON
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Release --target doc
