name: Publish documentation

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: ${{ github.workspace }}/vcpkg
        runVcpkgInstall: false

    - name: Install Emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 4.0.10
        actions-cache-folder: 'emsdk-cache'

    - name: Set build output dir
      id: strings
      shell: bash
      run: |
        echo "build-output-wasm-dir=${{ github.workspace }}/build-wasm" >> "$GITHUB_OUTPUT"
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Install Ninja
      run: sudo apt-get install -y ninja-build

    - name: Install Doxygen
      run: |
        sudo apt-get install -y graphviz
        wget https://github.com/doxygen/doxygen/releases/download/Release_1_12_0/doxygen-1.12.0.linux.bin.tar.gz
        tar -xf doxygen-1.12.0.linux.bin.tar.gz
        cd doxygen-1.12.0
        sudo make
        sudo make install
        doxygen --version

    - name: Configure CMake (JS module)
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-wasm-dir }} -S ${{ github.workspace }}
        -DVCPKG_TARGET_TRIPLET=wasm32-emscripten
        -DCMAKE_TOOLCHAIN_FILE=${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake
        -DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=${EMSDK}/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake
        -DCMAKE_CROSSCOMPILING_EMULATOR=${EMSDK_NODE}
        -DIDLC_BUILD_DOC=ON
        -DIDLC_BUILD_TOOL=OFF
        -DIDLC_USE_IDLC=ON
        -DIDLC_BUILD_PACKAGES=OFF
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_FLAGS="-fexceptions -Oz"
        -DCMAKE_CXX_FLAGS="-fexceptions -Oz"
        -DCMAKE_EXE_LINKER_FLAGS="-fexceptions -Oz"
        -DCMAKE_MAKE_PROGRAM=/usr/bin/ninja
        -DCMAKE_INSTALL_PREFIX=${{ steps.strings.outputs.build-output-wasm-dir }}/install
        -G Ninja
  
    - name: Build JS module
      run: |
        cmake --build ${{ steps.strings.outputs.build-output-wasm-dir }} --target install
        ${{ steps.strings.outputs.build-output-wasm-dir }}/vcpkg_installed/x64-linux/tools/idlc/idlc -g js -o ${{ steps.strings.outputs.build-output-wasm-dir }}/ -w ${{ github.workspace }}/specs/api.idl
        emcc -std=c++20 -I${{ steps.strings.outputs.build-output-wasm-dir }}/install/include/idlc -Wl,--whole-archive ${{ steps.strings.outputs.build-output-wasm-dir }}/install/lib/libidl.a ${{ steps.strings.outputs.build-output-wasm-dir }}/vcpkg_installed/wasm32-emscripten/lib/libfmt.a ${{ steps.strings.outputs.build-output-wasm-dir }}/vcpkg_installed/wasm32-emscripten/lib/libxxhash.a -Wl,--no-whole-archive ${{ steps.strings.outputs.build-output-wasm-dir }}/idlc.js.cpp -o ${{ github.workspace }}/doc/idlc.js -lembind -s WASM=1 -s MODULARIZE=1 -s ALLOW_MEMORY_GROWTH=1 -s EXPORT_NAME=idlc -s DISABLE_EXCEPTION_CATCHING=0 --emit-tsd idlc.d.ts -s EXPORT_ES6=1 -Oz -s SINGLE_FILE=1 -fexceptions

    - name: Configure CMake
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -S ${{ github.workspace }}
        -DIDLC_BUILD_DOC=ON
        -DIDLC_BUILD_TOOL=OFF
        -DIDLC_USE_IDLC=OFF
        -DIDLC_BUILD_PACKAGES=OFF
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_BUILD_TYPE=Release
        -G Ninja

    - name: Build Documentation
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --target doc

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.strings.outputs.build-output-dir }}/doc/html
